#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from core.config import ENVIRONMENT_VARIABLES


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "ENV.md"


def _render() -> str:
    lines = [
        "# Environment Variables",
        "",
        "> Auto-generated by `python3 scripts/build_env_doc.py`. Do not edit manually.",
        "> Generated from `scripts/core/config.py` so the checked-in docs and runtime env registry stay aligned.",
        "> Machine-specific default paths can be inspected with `python3 scripts/token_usage.py health --format json`.",
        "",
        "## Registry",
        "",
        f"- total env keys: `{len(ENVIRONMENT_VARIABLES)}`",
        "",
        "| variable | purpose |",
        "|---|---|",
    ]
    for item in ENVIRONMENT_VARIABLES:
        lines.append(f"| `{item['name']}` | {item['description']} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate docs/ENV.md from scripts/core/config.py.")
    parser.add_argument("--check", action="store_true", help="fail if the generated content differs from the checked-in file")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="output path")
    args = parser.parse_args()

    output_path = Path(args.output).expanduser()
    rendered = _render()
    if args.check:
        existing = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if existing != rendered:
            raise SystemExit(f"{output_path} is out of date; run python3 scripts/build_env_doc.py")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
