#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from token_usage import _build_adapters


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "COVERAGE.md"
CATEGORY_ORDER = (
    "Native Clients",
    "Coding CLI",
    "Desktop Clients",
    "Provider / API Families",
    "Fallback",
)


def _category_for_source(source_id: str) -> str:
    if source_id in {"codex", "claude-code", "claude-desktop", "opencode", "minimax-agent"}:
        return "Native Clients"
    if source_id in {"qwen-code-cli", "kimi-cli", "gemini-cli"}:
        return "Coding CLI"
    if source_id.endswith("-desktop"):
        return "Desktop Clients"
    if source_id.endswith("-api"):
        return "Provider / API Families"
    return "Fallback"


def _render() -> str:
    registry = _build_adapters()
    rows = []
    for adapter in registry.values():
        rows.append(
            {
                "source_id": adapter.source_id,
                "display_name": adapter.display_name,
                "provider": adapter.provider,
                "accuracy_level": adapter.accuracy_level,
                "in_default_rollup": bool(getattr(adapter, "default_selected", True)),
                "category": _category_for_source(adapter.source_id),
            }
        )
    rows.sort(key=lambda item: (CATEGORY_ORDER.index(item["category"]), item["source_id"]))

    lines = [
        "# Coverage",
        "",
        "> Auto-generated by `python3 scripts/build_coverage_doc.py`. Do not edit manually.",
        "> Generated from the runtime source registry behind `python3 scripts/token_usage.py sources --format json`.",
        "> Machine-specific `ready / not-found` state is intentionally omitted here; this file describes supported source IDs and their rollup contract.",
        "",
        "## Summary",
        "",
        f"- total source IDs: `{len(rows)}`",
        f"- default rollup source IDs: `{sum(1 for item in rows if item['in_default_rollup'])}`",
        f"- provider family source IDs: `{sum(1 for item in rows if item['category'] == 'Provider / API Families')}`",
        f"- desktop source IDs: `{sum(1 for item in rows if item['category'] == 'Desktop Clients')}`",
        "",
    ]

    for category in CATEGORY_ORDER:
        category_rows = [item for item in rows if item["category"] == category]
        if not category_rows:
            continue
        lines.extend(
            [
                f"## {category}",
                "",
                "| source_id | display_name | provider | accuracy | default_rollup |",
                "|---|---|---|---|---|",
            ]
        )
        for item in category_rows:
            lines.append(
                f"| `{item['source_id']}` | {item['display_name']} | `{item['provider']}` | `{item['accuracy_level']}` | `{str(item['in_default_rollup']).lower()}` |"
            )
        lines.append("")

    lines.extend(
        [
            "## Runtime Capture Paths",
            "",
            "- `ingress companion` 是运行时 capture path，不单独算 `source_id`；它会把 exact JSONL 落盘后交给 provider family 自动认领。",
            "- `generic-openai-compatible` 仍保留为 fallback，但默认不参与总览，避免和已拆分的 provider family 重复计数。",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate docs/COVERAGE.md from the runtime source registry.")
    parser.add_argument("--check", action="store_true", help="fail if the generated content differs from the checked-in file")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="output path")
    args = parser.parse_args()

    output_path = Path(args.output).expanduser()
    rendered = _render()
    if args.check:
        existing = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if existing != rendered:
            raise SystemExit(f"{output_path} is out of date; run python3 scripts/build_coverage_doc.py")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
